Analiza_piosenek/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from organizer import views as organizer_views
from users import views as users_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', users_views.register, name='user-register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='user-logout'),
    path('profile/', users_views.profile, name='user-profile'),
    path('upload/', users_views.profile, name='upload'),
    path('', organizer_views.home, name='mjuzik-home'),
    path('about/', organizer_views.about, name='mjuzik-about'),
    path('authors/', organizer_views.authors, name='mjuzik-authors'),
    path('songs/', organizer_views.songs, name='mjuzik-songs'),
    path('lajk_author/', organizer_views.lajk_author, name='lajk_author'),
    path('lajk_song/', organizer_views.lajk_song, name='lajk_song')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from .forms import ImageUploadForm
from django.contrib.postgres.fields import HStoreField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pics', default='kot_default.webp')
    liked_songs = ArrayField(models.IntegerField(), default=list, blank=True)
    liked_authors = ArrayField(models.IntegerField(), default=list, blank=True)
    authors_views = HStoreField(default=dict)
    songs_views = HStoreField(default=dict)

    def __str__(self):
        return f"{self.user.username} Profile"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ImageUploadForm(forms.Form):
    image = forms.ImageField()

users/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from users.forms import UserRegisterForm
from .forms import ImageUploadForm
from .models import Profile
from organizer.views import handle_base_cards, go_to_song_or_author


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            messages.success(request, f"Account created successfully. User '{username}' logged in")
            return redirect('mjuzik-home')
    else:
        form = UserRegisterForm()
    if request.method == 'GET':
        song_or_author_request = go_to_song_or_author(request)
        if song_or_author_request:
            return handle_base_cards(request, song_or_author_request[0], song_or_author_request[1])
    return handle_base_cards(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            m = Profile.objects.get(user_id=request.user.id)
            m.image = form.cleaned_data['image']
            m.save()
    if request.method == 'GET':
        song_or_author_request = go_to_song_or_author(request)
        if song_or_author_request:
            return handle_base_cards(request, song_or_author_request[0], song_or_author_request[1])
    return handle_base_cards(request, 'users/profile.html', {})

templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log in</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/users/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'user-login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

templates/users/profile.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="Can't load picture">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <div class="card">
        <h5 class="card-header">Change profile image</h5>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input id="id_image" type="file" class="" name="image">
                <button type="submit" value="submit" style="float: right">Upload file</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Account</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account?
                <a class="ml-2" href="{% url 'user-login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}